version: "3.8"

x-dotfiles: &dotfiles
  links:
    - socat
  image: "${GITHUB_USER:-${USER}}/dotfiles"
  tty: true
  stdin_open: true
  network_mode: host
  environment:
    - &DOCKER_HOST
      DOCKER_HOST=localhost:2375

services:

  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    expose:
      - 2375
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build:
    profiles:
      - build
    build:
      context: .
      args:
        USER: "$USER"

  dotfiles:
    <<: *dotfiles
    profiles:
      - dotfiles
  
  run:
    <<: *dotfiles
    profiles:
      - run
    working_dir: /working_dir
    volumes:
      - .:/working_dir
      - "$HOME/.ssh:/home/$USER/.ssh"
      - "$HOME/.config/git/config:/home/$USER/.config/git/config"
      - "$HOME/.config/gcloud:/home/$USER/.config/gcloud"
    environment:
      - *DOCKER_HOST

  mac:
    <<: *dotfiles
    profiles:
      - mac
    working_dir: /working_dir
    volumes:
      - .:/working_dir
      - "$HOME/.ssh:/home/$USER/.ssh"
      - "$HOME/.config/git/config:/home/$USER/.config/git/config"
      - "$HOME/.config/gcloud:/home/$USER/.config/gcloud"
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - *DOCKER_HOST
