version: "3.8"

x-dotfiles: &dotfiles
  build:
    context: .
    args:
      - USER
      - NAME
      - EMAIL
  tty: true
  stdin_open: true
  network_mode: host
  links:
    - socat
  environment:
    - &DOCKER_HOST DOCKER_HOST=localhost:2375

services:
  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    expose:
      - "2375"
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dotfiles:
    <<: *dotfiles
    profiles:
      - dotfiles
    volumes:
      - $PWD:$PWD

  build:
    <<: *dotfiles
    profiles:
      - build

  run:
    <<: *dotfiles
    profiles:
      - run
    working_dir: /working_dir
    volumes:
      - "$PWD:/working_dir"
      - "$HOME/.ssh:/home/$USER/.ssh"
      - "$HOME/.config/gcloud:/home/$USER/.config/gcloud"
      - "$HOME/.config/git/config:/home/$USER/.config/git/config"

  mac:
    <<: *dotfiles
    profiles:
      - mac
    working_dir: /working_dir
    volumes:
      - "$PWD:/working_dir"
      - "$HOME/.ssh:/home/$USER/.ssh"
      - "$HOME/.config/gcloud:/home/$USER/.config/gcloud"
      - "$HOME/.config/git/config:/home/$USER/.config/git/config"
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
      - *DOCKER_HOST
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
