version: "3.8"
services:
  socat:
     image: bpack/socat
     command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
     network_mode: "host"
     volumes:
        - /var/run/docker.sock:/var/run/docker.sock
     expose:
        - "2375"
  dotfiles:
    links:
      - socat
    image: jasonmorganson/dotfiles
    tty: true
    stdin_open: true
    network_mode: "host"
    working_dir: "/home/$USER/working_dir"
    volumes:
      - "$PWD:/home/$USER/working_dir"
      - "$HOME/.ssh:/home/user/.ssh:cached"
      - "$HOME/.config/git/config:/home/user/.config/git/config:cached"
      - "$HOME/.config/gcloud:/home/user/.config/gcloud:cached"
      - "$SSH_AUTH_SOCK:/ssh-agent"
    environment:
      - DOCKER_HOST=localhost:2375
      - "SSH_AUTH_SOCK=/ssh-agent"
