
name: Test install script in devcontainer

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user 1000
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: ./install.sh