name: Test install script

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Run install script
      env:
        USER: jasonmorganson
        NAME: "Jason Morganson"
        EMAIL: jason@cherre.com
      run: ./install.sh
